### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by platinumdragon7** [colinwarn/alexaraspberrypilightautomation#1]
Can you add the script you used in Alexa skill?

**Comment by colinwarn** [comment]
{
    "interactionModel": {
        "languageModel": {
            "invocationName": "ground control",
            "intents": [
                {
                    "name": "PartyModeIntent",
                    "slots": [],
                    "samples": [
                        "party mode",
                        "lets get funky",
                        "start the party"
                    ]
                },
                {
                    "name": "LightsOnIntent",
                    "slots": [],
                    "samples": [
                        "lights on"
                    ]
                },
                {
                    "name": "LightsOffIntent",
                    "slots": [],
                    "samples": [
                        "lights off"
                    ]
                },
                {
                    "name": "PartyModeStopIntent",
                    "slots": [],
                    "samples": [
                        "stop the party",
                        "party mode stop"
                    ]
                }
            ],
            "types": []
        }
    }
}
